version: '3'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    ports:
      - 8000:3000
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - /data/docker/etc/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations

  homeassistant:
    container_name: ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data/docker/ha:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    volumes:
      - /data/docker/kuma:/app/data
    ports:
      - 8001:3001
    restart: always

  moviepilot:
    image: jxxghp/moviepilot:1.9.2
    container_name: moviepilot
    network_mode: host
    volumes:
      - /data/docker/etc/moviepilot:/config
      - /data/docker/moviepilot/data:/moviepilot
      - /data/media:/media
      - /data/downloads:/downloads
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - AUTH_SITE=$AUTH_SITE
      - IYUU_SIGN=$IYUU_SIGN
      - ICC2022_UID=$ICC2022_UID
      - ICC2022_PASSKEY=$ICC2022_PASSKEY
      - BIG_MEMORY_MODE=true
      - AUTO_UPDATE_RESOURCE=false
      - PROXY_HOST=socks5://openwrt.lan:1081
      - MOVIEPILOT_AUTO_UPDATE=false
      - PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins,https://github.com/thsrite/MoviePilot-Plugins
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /data/docker/etc/qbittorrent:/config
      - /data/downloads:/downloads
    restart: unless-stopped

  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /data/docker/etc/emby:/config # Configuration directory
      - /data/docker/emby:/data
      - /data/media:/media # Media directory
      - /data/downloads:/downloads
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: on-failure

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # network_mode: 'host'
    ports:
      - 8097:8096 # HTTP port
    volumes:
      - /data/docker/etc/jellyfin:/config # Configuration directory
      - /data/docker/jellyfin/cache:/cache
      - /data/media:/media # Media directory
    restart: 'unless-stopped'
