version: '3'
services:
  homeassistant:
    container_name: ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data/docker/ha:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    volumes:
      - /data/docker/kuma:/app/data
    ports:
      - 3001:3001
    restart: always

  moviepilot:
    image: jxxghp/moviepilot:latest
    container_name: uptime
    volumes:
      - /data/docker/moviepilot/downloads:/downloads
    ports:
      - 3001:3001
    restart: always
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /data/docker/qbittorrent/config:/config
      - /data/docker/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped