version: '3'
services:
  homeassistant:
    container_name: ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data/docker/ha:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    volumes:
      - /data/docker/kuma:/app/data
    ports:
      - 3001:3001
    restart: always

  moviepilot:
    image: jxxghp/moviepilot:latest
    container_name: moviepilot
    network_mode: host
    volumes:
      - /data/docker/etc/moviepilot:/config
      - /data/docker/moviepilot/data:/moviepilot
      - /data/docker/moviepilot/media:/media
      - /data/docker/moviepilot/downloads:/downloads
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    restart: always
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /data/docker/etc/qbittorrent:/config
      - /data/docker/moviepilot/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /data/docker/etc/emby:/config # Configuration directory
      - /data/docker/moviepilot/media:/data # Media directory
      - /data/docker/moviepilot/downloads:/downloads
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: on-failure